### ISSUE TITLE
Issue: Cant get Windows ISO Download

### ISSUE THREAD

**Issue by En3rgY17** [diddlesnaps/clouds#14]
### What happened?

I walked through the entire ISO config, when it tried to download the ISO, it just said:  Failed to get Windows ISO image download URL

### What should have happened?

It should download the ISO just as normal

### Output of `snap info clouds`

```plain text
name:      clouds
summary:   Download, install, and run Windows in a VM
publisher: Dani Llewellyn (diddledani✪)
store-url: https://snapcraft.io/clouds
contact:   https://github.com/diddlesnaps/clouds/issues
license:   unset
description: |
  Download, install, and run Windows 10 or 11 in a VM.
  
  The app will walk you through downloading a Windows DVD image, and launch
  the installation. Most of the installation is automated to reduce the
  chance of errors while installing. Once Windows is installed Clouds will
  boot directly into the operating system whenever you launch the app.
commands:
  - clouds
  - clouds.mid
  - clouds.mp3
snap-id:      5sTqSTu8Oj8VOeLa0vqludrUmP5nKVsq
tracking:     latest/edge
refresh-date: today at 10:54 CET
channels:
  latest/stable:    0.666 2022-08-23 (48) 315MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      0.666 2022-11-02 (49) 314MB -
installed:          0.666            (49) 314MB -
```

### Output of `snap connections clouds`

```plain text
Interface               Plug                           Slot                            Notes
audio-playback          clouds:audio-playback          :audio-playback                 -
audio-record            clouds:audio-record            -                               -
content[gnome-42-2204]  clouds:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   clouds:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    clouds:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   clouds:sound-themes            gtk-common-themes:sound-themes  -
desktop                 clouds:desktop                 :desktop                        -
desktop-legacy          clouds:desktop-legacy          :desktop-legacy                 -
gsettings               clouds:gsettings               :gsettings                      -
home                    clouds:home                    :home                           -
kvm                     clouds:kvm                     :kvm                            -
network                 clouds:network                 :network                        -
network-bind            clouds:network-bind            :network-bind                   -
network-control         clouds:network-control         -                               -
opengl                  clouds:opengl                  :opengl                         -
raw-usb                 clouds:raw-usb                 :raw-usb                        manual
removable-media         clouds:removable-media         :removable-media                manual
screen-inhibit-control  clouds:screen-inhibit-control  :screen-inhibit-control         -
wayland                 clouds:wayland                 :wayland                        -
x11                     clouds:x11                     :x11
```

### Output of `snap version`

```plain text
snap    2.58+22.10
snapd   2.58+22.10
series  16
ubuntu  22.10
kernel  5.19.0-29-generic
```

### Teminal output of app

```plain text
*** Checking for kvm interface connection
INFO: kvm interface is connected
*** Checking for Downloaded Windows ISO
TypeError: Cannot read properties of null (reading '0')
    at fetchDownloadUrl (file:///snap/clouds/49/lib/node_modules/downloader/index.mjs:39:91)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///snap/clouds/49/lib/node_modules/downloader/index.mjs:50:26
INFO: ISO download URL=
ERROR: Failed to get Windows ISO image download URL

(yad:12078): Gdk-CRITICAL **: 12:36:08.433: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
```

**Comment by PolyBreaker0** [comment]
I´m having the same issue, How can I use iso downloaded elsewhere? 
Is there any path where I can put it manually?

**Comment by MarkWalder2** [comment]
So did this issue ever get sorted, just downloaded this app on the latest Ubuntu and it has the very same issue , Failed to get Windows ISO image download URL
